### ISSUE TITLE
Image placing item

### ISSUE THREAD

**Issue by wtlgo** [josemmo/yamipa#10]
Hello, I would like to suggest a feature. 
It would be nice to have the ability to create an item that will place the image without the usage of commands and make images placed by this item breakable. Would it be very difficult to implement?

**Comment by josemmo** [comment]
Hi, @wtlgo!

This looks like an interesting concept. Could you explain it a bit further? Do you mean creating an "image" item that can be placed and broken like a in-game block, for instance?

**Comment by wtlgo** [comment]
Ah, I mean that player has the item, right clicks on the split block, the image which is assigned to the item appears on that block, and the item disappears from the players' inventory.
Then he left clicks the image, the image gets removed and the item is dropped back to the player.
More like normal map-arts work, but without placing frames in advance, I guess.
I hope I was clear this time.

**Comment by josemmo** [comment]
Got it! Not the easiest thing to implement but it's probably feasible.

Here's the spec I'm aiming for:

- A new command (let's say "/yamipa give <player> [...]") will be added to allow issuing **image items** to a player.
- This image items have a predefined set of attributes (image file, width and height) that are defined when the "give" command is called, and are stackable as long as they have the same attributes tuple.
- Image items **can be placed on block surfaces** using the interact button (right click by default). After placing an image item, it gets removed from the player's inventory.
- Unlike images placed using commands, images which originated from an image item **can be removed by any player** with the attack/destroy button (left click by default), dropping the original image item in the process.
- Destroying the block an image item was placed upon will *not* remove the image to allow the placing of floating images.

In the meantime I'll focus on the next Yamipa release (animated images + 1.18 compatibility), this if implemented will be released later.

**Comment by wtlgo** [comment]
Yeah, of course, take your time, I just gave an idea. Initially, I planned to implement this by myself and just make a pull request but sadly turned out that I'm not as good at Java as I thought, so the only option I had is to tell you what I tried to make and failed. Thank you very much for listening!

**Comment by josemmo** [comment]
Good news!

Placeable items has landed in pre-release [v1.2.1-SNAPSHOT](https://github.com/josemmo/yamipa/releases/tag/v1.2.1-SNAPSHOT). You can find the documentation at [this link](https://github.com/josemmo/yamipa/tree/develop#readme).

Let me know if you find any bugs.

**Comment by wtlgo** [comment]
I am very excited to try it out! I'll let you know if I stumble upon any issues.

**Comment by wtlgo** [comment]
Hello, so after using this version on my server for a while, I think it works very well!
There is a minor issue though. Sometimes when the item is dropped it spawns inside of the block, and clips into a random location behind the wall or in the cave below.

I'm not sure, but I think its because of what happens here, where it takes the exact location of the attacked block
https://github.com/josemmo/yamipa/blob/5710f5abdea3bb0cde3737e5277b403784564398/src/main/java/io/josemmo/bukkit/plugin/renderer/ItemService.java#L144
and then, if I understand correctly, tries to spawn it inside of this block.
https://github.com/josemmo/yamipa/blob/5710f5abdea3bb0cde3737e5277b403784564398/src/main/java/io/josemmo/bukkit/plugin/renderer/ItemService.java#L158
Maybe moving the location one block towards the attacked face would make things better?

**Comment by josemmo** [comment]
Good catch!

I've sent a commit which should have fixed it.
Looks like this feature is ready, so I'm closing this issue and expect to ship it in the next release! :)
