### ISSUE TITLE
"/image download" is not working

### ISSUE THREAD

**Issue by Slamm33** [josemmo/yamipa#100]
![image](https://github.com/josemmo/yamipa/assets/131832521/a7871674-dfd9-42f9-9fea-97e30d3625d0)

I play on 1.20 Paper and I'm using the latest versions of ProtocolLib and Yamipa

![image](https://github.com/josemmo/yamipa/assets/131832521/7bc560b3-e655-40ee-a68c-b4681fba60b6)

It works without symbols.

**Comment by josemmo** [comment]
@Slamm33, you need to wrap the URL between quotes:
```
/image download "https://example.com/image.png" destination.png
```
