### ISSUE TITLE
Restrict max placed size of an image

### ISSUE THREAD

**Issue by makeevrserg** [josemmo/yamipa#102]
#### Example:
Player with permission `yamipa.command.place.width.10` and `yamipa.command.place.height.10` can place images with width max by 10x10 blocks
If there's no `yamipa.command.place.height/width` than player is not restricted to place any sizes

**Comment by josemmo** [comment]
Hi, @makeevrserg!

This feature is out of scope for the project. You can restrict the size of images by giving your players images items instead of letting them use place commands. Check [the documentation](https://github.com/josemmo/yamipa#usage) for more information.
