### ISSUE TITLE
Capability with lower version with ViaVersion plugin

### ISSUE THREAD

**Issue by azzztec** [josemmo/yamipa#107]
I have ViaVersion installed on my 1.17.1 sever with support 1.16.5 - 1.20.2 versions. In versions from 1.17.1 plugin works well, but on versions lower 1.17.1(1.13 - 1.16.5) images are corrupted:
![image](https://github.com/josemmo/yamipa/assets/57875019/7bd5a851-f74a-4c51-b3fd-58e3ae4eeabf)

Is it possible to solve that in future?

Plugin version: 1.2.12
Server: purpur-1.17.1-1428

**Comment by josemmo** [comment]
Hi @azzztec,

Not sure how ViaVersion works internally, but I presume it intercepts the protocol injector from ProtocolLib if installed.

For performance, Yamipa hooks directly to the `PlayerInjectionHandler` class of ProtocolLib, which may be causing the issue:
https://github.com/josemmo/yamipa/blob/076d9990056762212b322456aeb0d09770d97232/src/main/java/io/josemmo/bukkit/plugin/renderer/FakeEntity.java#L22-L37

Could you trying building Yamipa with those lines commented out (22 to 37) to see if it then works?

**Comment by azzztec** [comment]
> Hi @azzztec,
> 
> Not sure how ViaVersion works internally, but I presume it intercepts the protocol injector from ProtocolLib if installed.
> 
> For performance, Yamipa hooks directly to the `PlayerInjectionHandler` class of ProtocolLib, which may be causing the issue:
> 
> https://github.com/josemmo/yamipa/blob/076d9990056762212b322456aeb0d09770d97232/src/main/java/io/josemmo/bukkit/plugin/renderer/FakeEntity.java#L22-L37
> 
> Could you trying building Yamipa with those lines commented out (22 to 37) to see if it then works?

Same result. Also i am using in my purpur-1.16.5-1171 server YamipaPlugin-1.2.11 and it works in all versions from 1.13 to 1.20.1

**Comment by josemmo** [comment]
Then, AFAIK, there's not much we can do from this plugin's perspective.

Yamipa automatically detects the version of your server and crafts the appropiate network packets based on that. If ViaVersion is not rewriting those packets, then I'd need to debug that other plugin to understand what's going on, and I'm not familar enough to take on that challenge.
