### ISSUE TITLE
1.20.2 - Can't place image

### ISSUE THREAD

**Issue by snorkelsaur** [josemmo/yamipa#108]
Good morning!

I see support for Paper 1.20.2 was recently added, the addon is now appearing in-game correctly. I used the commands below to try and place an image with the right click mouse button on desired block, but nothing happens:

/image place DMCBanner.png 8
/image place DMCBanner.png 8 3
/image place DMCBanner.png 8 3 +GLOW

I am receiving no errors and the image name does appear in the image list.

Any help is appreciated! Thank you!

**Comment by josemmo** [comment]
Hi, @snorkelsaur!

- What version of Paper are you using? _e.g., MC 1.20.2 build 260_
- What ProtocolLib version are you using? _e.g., v5.1.0_
- On what version of Yamipa does this bug occur? _e.g., v1.2.12_
- Does Yamipa raise any warning or error entries in the server logs? If so, paste them in this thread.
