### ISSUE TITLE
Minecraft 1.18 compatibility

### ISSUE THREAD

**Issue by AmIlluminati** [josemmo/yamipa#11]
Plugin refuses to work on 1.18, I know that the latest release is 1.17, but it refuses to load on 1.18.

**Comment by josemmo** [comment]
Hi @AmIlluminati,

That's because Minecraft 1.18 came just a few days ago! 😜
Anyways, I've made some changes to add support for 1.18 and released a new Yamipa version ([v1.2.0](https://github.com/josemmo/yamipa/releases/tag/v1.2.0)).
