### ISSUE TITLE
Not working on PaperMC 1.20.4

### ISSUE THREAD

**Issue by CptGummiball** [josemmo/yamipa#110]
Unfortunately the plugin no longer works with PaperMC 1.20.4.

https://paste.gg/p/anonymous/feb7da5d365b4b79b7a217648de7ae9b

We use Build 346 from PaperMC

**Comment by josemmo** [comment]
Use the latest ProtocolLib experimental build for 1.20.4: https://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/
