### ISSUE TITLE
Images are not usable after downloading them using itzg/docker-minecraft-server

### ISSUE THREAD

**Issue by senolem** [josemmo/yamipa#114]
Hello,
I have a server hosted in a docker-compose using the itzg/docker-minecraft-server image
When I download images it works and places them correctly in yamipa's images folder, but then when using /image give or /image list the image simply doesn't exists
![image](https://github.com/josemmo/yamipa/assets/37041587/d898dd53-5a95-4748-a32b-7cb1610a41b8)
![image](https://github.com/josemmo/yamipa/assets/37041587/22bc57d1-e86f-4864-bdb3-cf9e863a02c3)

Any idea what's going on here? the data folder is mounted between the host and the container, but that shouldn't be an issue...
thanks

**Comment by senolem** [comment]
Looks like it works now, probably happened after a reboot of the container... Would love to know why :(

**Comment by josemmo** [comment]
Hello @senolem,

Could you set `verbose: true` in the [Yamipa configuration file](https://github.com/josemmo/yamipa?tab=readme-ov-file#configuration) and paste the server logs here?

**Comment by senolem** [comment]
![image](https://github.com/josemmo/yamipa/assets/37041587/b078f8c6-e265-470a-bb6e-226b91c8860a)

nothing interesting...

**Comment by josemmo** [comment]
You can build the project by cloning the repository and opening it in IntelliJ IDEA. Then, click on the Maven tab on right on the screen and double click "Lifecycle" > "Package". This should have created a JAR file on the "target" directory inside the project.

I don't think it's related to the [ImageStorage#isPathAllowed()](https://github.com/josemmo/yamipa/blob/17c59ea00eb71049a08f4e94fc0423149e664d86/src/main/java/io/josemmo/bukkit/plugin/storage/ImageStorage.java#L152) method, as you should have seen debug logs on the server console at download regardless of your plugin configuration.

This must have something to do with Java's WatchService class and inotify on Linux (see [this link](https://blog.arkey.fr/2019/09/13/watchservice-and-bind-mount/)). When I find some time, I'll try to reproduce the bug on a container.

**Comment by senolem** [comment]
Thanks I managed to build it.

`if (isPathAllowed(filename, sender)) {
                response.add(filename);
            } else {
				LOGGER.warning("Unallowed path detected in the registered files map");
			}`

I tried to add a warning but it doesn't show up, sorry for the wrong assumption.

Maybe freshly created files are not mounted the same way than existing files during startup of the container, leading to the issue mentionned in the article.

**Comment by josemmo** [comment]
Hi, @senolem!

Could you verify that this issue is now fixed in the [v1.3.2-SNAPSHOT](https://github.com/josemmo/yamipa/releases/download/v1.3.2-SNAPSHOT/YamipaPlugin-1.3.2-SNAPSHOT.jar) pre-release version of Yamipa?

**Comment by RedstoneFuture** [comment]
@senolem 
Would you like to test it again? (with Minecraft < 1.20.6)
