### ISSUE TITLE
adding any flag will make the image not removable without /image remove

### ISSUE THREAD

**Issue by g0ldyy** [josemmo/yamipa#119]
title ^

**Comment by g0ldyy** [comment]
+ GLOW doesn't even work

**Comment by g0ldyy** [comment]
I have a server with lots of people who love your plugin and honestly, thank you for that. 
I'd really appreciate it if you could fix these issues :D

**Comment by josemmo** [comment]
Hello @g0ldyy,

Which command, including all parameters, are you using to place an image?

**Comment by g0ldyy** [comment]
I use the /image give image.gif 1 1 1 FLAG command and place it manually.
Any flag added at the end of the command will make the image impossible to remove manually (only possible with /image remove). It does this with any image or gif and any size.

**Comment by josemmo** [comment]
You're overwriting the default flags. To add a flag, you need to write "+FLAG" instead of "FLAG".
For more information, check the [documentation](https://github.com/josemmo/yamipa?tab=readme-ov-file#flags) of Yamipa.
