### ISSUE TITLE
Folia Support

### ISSUE THREAD

**Issue by Bufferless** [josemmo/yamipa#124]
Looking forward to using it on the latest Folia 1.20.4.

**Comment by josemmo** [comment]
Support for Folia is currently not expected in the near future. Will be revised when Folia reaches a more stable state.

**Comment by Tuchan** [comment]
> Looking forward to using it on the latest Folia 1.20.4.

https://github.com/Tuchan/yamipa/commit/c14d9aa3a4e555b127e9857589de3a8a863cb3b4 [1.20.1]

other than a few packet error messages when clicking the image, it should be usable @Bufferless
