### ISSUE TITLE
Animation stops.

### ISSUE THREAD

**Issue by NamiUni** [josemmo/yamipa#13]
The animation frame may stop. No error log is output to the console.

> This server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)
You are running the latest version
Previous version: git-Paper-353 (MC: 1.17.1)

> YamipaPlugin version 1.2.0

> ProtocolLib version 4.7.0

**Comment by josemmo** [comment]
Hi, @NamiUni!

Could you provide the list of installed plugins for the affected server, including their versions?

In the meantime, make sure the server logs contain the entry "Enabled image animation support" when Yamipa is enabled.

**Comment by NamiUni** [comment]
Thank you for your reply. Here is the plugin list.
> BlueMap 1.7.2
Bungeeguard 1.2
BungeeTabListPlus 3.4.4
Citizens 2.0.28-SNAPSHOT build2394
CMI 9.0.4.1
CMIlib 1.0.4.3DeluxeHub 3.3.10
DiscordSRV 1.24.0
Gsit 6.0.4.0
JukeBox 1.20.6
LoginInterphone 3.3.0
LuckPerms 5.3.74
LunaChat 3.0.16
NoteBlockAPI 1.6.1-SNAPSHOT
PlaceholderAPI 2.10.10
ProtocolLib 4.7.0
VoxelSniper 6.1.2
WorldEdit 7.2.7+9f3e795
WorldEditSelectionVisualizer 2.0.6
WorldGuard 7.0.6+1cff55f
YamipaPlugin 1.2.0

I was able to confirm that "Enabled image animation support" was output in the log.
The image is placed in the spawn chunk and animates for a while, but stops when you notice it.
I have two different images installed, and they both stop. I don't know if they stop at the same time.

I'll upload the plugins folder as well. If there is anything else you need, please let me know :)
[Yamipa.zip](https://github.com/josemmo/yamipa/files/7681867/Yamipa.zip)

**Comment by NamiUni** [comment]
I restarted the server and watched the images for a while, but after about an hour, one of the three placed images stopped animating.

**Comment by josemmo** [comment]
I've tried reproducing the bug in a local Purpur 1.17.1 server, left the server running for an hour and when I came back the animated image I placed was still playing.

If there are no error messages being logged by Yamipa it's probably caused by something else. Does your server have a firewall or some kind of tool for intercepting/blocking network packets?

**Comment by NamiUni** [comment]
No, I don't really use any tools like that.
However, it seems likely that other plugins and such are causing the problem.
I will try to verify some more things myself.
Thank you very much for taking your valuable time to help me with this issue of mine.

**Comment by josemmo** [comment]
Great! Let me know when you find the root cause, I'll leave the issue open for a few more days.

**Comment by NamiUni** [comment]
Hmmm, I couldn't figure out what the cause was after all, so I'll close this issue for now.
