### ISSUE TITLE
Error when starting server with images in renamed world

### ISSUE THREAD

**Issue by Hasenzahn1** [josemmo/yamipa#139]
# Description
When deleting/renaming a world in which images are placed, the plugin throws an error for every image in the renamed/deleted world. (See the error provided below). This is followed with no image being displayed in the renamed world. 

# Steps to reproduce the error
- Create a world using e.g multiverse.
- Place some images in the created world.
- Stop the server and rename the world (renaming the folder) 
- Start the server (the errors are printed in the console)
- Reimport the renamed world with multiverse
- Teleport to the imported world.

# How to solve the problem
- There should be a warning similar to the warning when deleting/renaming an image file. 
- Add a Command to replace the old world with the new world for all images in the database (eg. /image convert \<old-world> \<new-world>)
- Add a Command to remove all images in a single world. (e.g /image purge \<world>)

# Error log
https://pastebin.com/HL3TGsXj

**Comment by josemmo** [comment]
Hello @Hasenzahn1,

Yamipa has no way of knowing you renamed the world directory. Fortunately, this has an easy fix: just replace all occurrences of your world name in "plugins/YamipaPlugin/images.dat".
