### ISSUE TITLE
Server RAM usage

### ISSUE THREAD

**Issue by slendyduck** [josemmo/yamipa#15]
So I have a small server of around 20-25 people, and we have a few images around our town. As of now, this uses a few GB of ram... is there a way the plugin might be able to log the image into the actual storage instead of the memory?

**Comment by slendyduck** [comment]
Or, if possible, could you perhaps explain how the images are loaded into the RAM? And perhaps a theory why so much of it can be used at one given time? Because one of my players once placed a lot of images, and that drastically used lots of RAM... I understand that's my problem, but would there be any way to minimize this possibility?

**Comment by josemmo** [comment]
Hello @slendyduck,

Have a look at the [How does it work?](https://github.com/josemmo/yamipa#how-does-it-work) section in the Yamipa documentation.
