### ISSUE TITLE
Proposal to add support for glow item frame.

### ISSUE THREAD

**Issue by August7** [josemmo/yamipa#16]
The current image is realized by a fake item frame, and in minecraft1.17 added a new item: glow item frame. Their visual effects are quite different, especially at low brightness.  Therefore, it is proposed to add the use of a glow item frame base as one of the options for placing pictures.

**Comment by josemmo** [comment]
Hello @August7,

AFAIK glow item frames are different from regular frames in that they emit light, right? Meaning images placed in glow item frames will be visible even in completely dark areas.

In terms of UI, will adding a "flags" argument to the place command work for you?
```
/image place <filename> <width> [<height>] [<flags>]
```

For example, to place a glowing image:
```
/image place image.jpg 3 2 +GLOW
```

**Comment by August7** [comment]
@josemmo I think this is great.

**Comment by artemr13** [comment]
Hi @josemmo
Thank you for your best image on frames plugin.
I wanted to ask, is the function of adding flags fully completed? If so, release please.
Also, what the flags +ANIM +DROP +REMO are for? (See it in your commit)
