### ISSUE TITLE
Some placed images can't be removed by hand, using the remove or clear command hangs the server

### ISSUE THREAD

**Issue by NeuTraLZero** [josemmo/yamipa#20]
Some images work just fine but some of them are just stuck there and can't be removed at all, I tried doing kill command also but it didn't work. Using the built in commands to remove them cause everyone on the server to not be able to break and place blocks until a restart

Paper 1.18.1 build #133
Yamipa version 1.2.1

**Comment by NeuTraLZero** [comment]
Update: seems to only happen when you place the picture on non-solid blocks like glass and composter. 2x2 and higher can be fixed by changing the blocks behind the picture and punching it but 1x1 pictures will stay there permanently

**Comment by josemmo** [comment]
Hi, @NeuTraLZero!

> I tried doing kill command also but it didn't work

What "kill" command are you referring to? The vanilla one?

---

> Using the built in commands to remove them cause everyone on the server to not be able to break and place blocks until a restart

Wow, this looks concerning. What built-in command are you using to remove the images?

---

> Update: seems to only happen when you place the picture on non-solid blocks like glass and composter

Thanks for the info! I'll try to have a look at it tomorrow.

**Comment by NeuTraLZero** [comment]
> What "kill" command are you referring to? The vanilla one?
Yep.

> Wow, this looks concerning. What built-in command are you using to remove the images?
'/yamipa remove' will only freeze block updates for about 5 seconds but '/yamipa clear' seems to be the most concerning, this also happens with '/yamipa describe' for some reason

btw this problem doesn't yield any console errors

**Comment by josemmo** [comment]
> Update: seems to only happen when you place the picture on non-solid blocks like glass and composter

I was able to reproduce this on glass, composter and leaf blocks.
Will start working on a fix.

**Comment by josemmo** [comment]
@NeuTraLZero, a couple of additional questions.

> What "kill" command are you referring to? The vanilla one?

What are you using the "kill" command for?

---

> '/yamipa remove' will only freeze block updates for about 5 seconds but '/yamipa clear' seems to be the most concerning, this also happens with '/yamipa describe' for some reason

Could you elaborate a bit more on this? What happens exactly when you run these commands? Why is the "clear" command the most concerning? Please include full commands.

---

> btw this problem doesn't yield any console errors

Then this is going to be quite difficult to debug and fix. Isn't there a "Can't keep up! Is the server overloaded? Running XXXms or XXX ticks behind" entry? Paper will create a server thread dump when things like this happen.

**Comment by josemmo** [comment]
Should be fixed in the latest snapshot ([v1.2.2-SNAPSHOT](https://github.com/josemmo/yamipa/releases/download/v1.2.2-SNAPSHOT/YamipaPlugin-1.2.2-SNAPSHOT.jar)), try it out and let me know if it's solved.

**Comment by NeuTraLZero** [comment]
Both fixed with the lastest snapshot
