### ISSUE TITLE
Weird Yamipa bug. Teleporting between worlds break signs in intial chunks.

### ISSUE THREAD

**Issue by Wolvend** [josemmo/yamipa#24]
We have a reoccurring bug where ever we create yamipa pictures near warps they don't load until players move out of the chunks and reloads them. If the warp is between different worlds such as /spawn or /warp nether that will load some or no yamipa images. Gifs seem to be more consistent loading half to some of the image placed. We are running on a 3950x with 3 cores and 12gb of RAM. Perfect TPS no lag. On the latest 1.18.1 paper build with CMI for warps and Multiverse-core for our worlds.

To recreate this simply create a paper server with multiverse worlds and use the /mvtp command between them. Any close proximity chunks between a radius of approximately 150 blocks will break signs. If you fly away enough for the itemframes to despawn they will load without issues when you fly back.

Please help us figure out whats going on because it breaks our signs between our tutorial world and spawn. Thanks a lot for the cool plugin!

**Comment by Wolvend** [comment]
There are no errors to report in console. Yamipa is working perfectly fine and doesn't show any issues beyond the visual bug.

**Comment by NeuTraLZero** [comment]
Can confirm that this also happens in my server

**Comment by josemmo** [comment]
Tested on a Paper server with Multiverse using the "/mvtp" command, was able to reproduce the bug consistently everytime I teleported from a vanilla world ("world" or "world_nether") to a custom server world.

**Comment by josemmo** [comment]
I think I found the issue and managed to fix it.
Please try the latest snapshot ([v1.2.2-SNAPSHOT](https://github.com/josemmo/yamipa/releases/download/v1.2.2-SNAPSHOT/YamipaPlugin-1.2.2-SNAPSHOT.jar)) and let me know whether it's fixed.

**Comment by Wolvend** [comment]
Thank you! Fix seems to work. I'm trying really hard to recreate it to no avail. So it seems to finally be patched.

**Comment by josemmo** [comment]
Great! I'm closing the issue and will release the fix with the next update.
