### ISSUE TITLE
Animated GIF images unable to handle transparency.

### ISSUE THREAD

**Issue by Wolvend** [josemmo/yamipa#27]
I don't know if this is due to limitations, but whenever I upload a gif with a transparent background it won't update the empty pixels. It will only reset once the gif has gone through it's cycle. Maybe add an exception in the image create command for uploading transparent gifs to force render empty pixels as well?
![2022-01-20_16 28 52](https://user-images.githubusercontent.com/69109386/150444225-4bae8bc0-c234-4566-95f0-564d9d42f999.png)
![2022-01-20_16 28 42](https://user-images.githubusercontent.com/69109386/150444236-3fe20c06-0aef-4c8e-b349-0af8383569f8.png)

**Comment by josemmo** [comment]
Yup, Yamipa does not support animated GIF files... yet.

Could you provide a sample GIF file I can use for testing? Looks like an interesting feature to add.

**Comment by josemmo** [comment]
I've just published a new release with support for animated transparent GIF files: [v1.2.2](https://github.com/josemmo/yamipa/releases/tag/v1.2.2)

**Comment by Wolvend** [comment]
AWESOME. WORKS GREAT.
