### ISSUE TITLE
Plugin not loading on 1.17

### ISSUE THREAD

**Issue by MatsG23** [josemmo/yamipa#3]
Hello!

Although you say in the Bukkit Download site that 1.17 wouldn't be a problem _(
Requirements: CraftBukkit, Spigot or PaperMC v1.16 or v1.17)_,
I'm having following errors in my server console

https://pastebin.com/xxSGqmTK

An update to the newest NBT-API will probably fix it.

Best Regards
Mats

**Comment by josemmo** [comment]
Hi @MatsG23,

Yamipa v1.0.4 is not compatible with MC 1.17. Try using [v1.1.0-SNAPSHOT](https://github.com/josemmo/yamipa/releases/tag/v1.1.0-SNAPSHOT) (v1.1.0 stable will be released shortly).

**Comment by MatsG23** [comment]
Alright!
