### ISSUE TITLE
Feature request: Yamipa aware if a client is bedrock. (Gifs too fast)

### ISSUE THREAD

**Issue by Wolvend** [josemmo/yamipa#39]
We use Geyser on our server with bedrock functionality. I've noticed a reoccurring problem where there is no such thing as transparent image frames on mobile. While this is a nuisance, if Yamipa had a way to send itemframes based on player's client, we would be able to make solid pictures for mobile, and transparent for java. Geyser has support for telling if a client is bedrock.

We also noticed where GIF frames update too frequently for mobile, and they will force disconnect. Could there be a way to config gifs to load in fewer frame updates so there isn't packet overload? I haven't been able to use gifs on bedrock unless they're very small.

**Comment by josemmo** [comment]
Hi @Wolvend,

As I've said in other occasions, Minecraft is not in any way designed to place custom images on the world. To achieve this, Yamipa does [some weird stuff](https://github.com/josemmo/yamipa#how-does-it-work) the game wasn't built to handle.

Minecraft Java Edition and Bedrock are nothing alike, so just dropping Geyser or a similar packet translator won't work. In fact, the issue you mention about the transparent images is even [acknowledge](https://wiki.geysermc.org/geyser/current-limitations/) by the Geyser developers as a limitation of Bedrock's protocol.

**Comment by tdherring** [comment]
Hi! I think what's being requested here is the ability to send a different image to Bedrock vs Java clients. For example:

Java Client: `imgA.gif`
Bedrock Client: `imgB.png`

This would be a really useful feature to deal with the lag associated with GIFs on Bedrock clients. Obviously the `/yamipa give` command would have to be changed (maybe as simple as adding an optional second image file param - if not specified applies to both java and bedrock), a bit like `/yamipa give <player> <img> [bedrock_img] <amount> <width> <height>`.

I hope this makes sense.
