### ISSUE TITLE
Support for downloading Imgur.com URLs

### ISSUE THREAD

**Issue by ozyloc** [josemmo/yamipa#40]
Hi. I recently got this plugin for my Minecraft server, and it works well. For just the first image. I tried to use more images after that, but every single one I upload after the first it says "The requested file is not a valid image"
What happened?
I use Imgur to upload the images, should I use something else.
The plugins on my server are LuckPerms, WorldEdit, Essentials, EndermanNoAnger, ClearLag, GSit, SilkTouchHands, Geyser/Floodgate, LuckPermsChat, Multiverse core, Graves, Multiverse Portals, and CCTV. Are there any plugins that are incompatible?

**Comment by ozyloc** [comment]
I also use spigot, if that helps.

**Comment by josemmo** [comment]
Hi @ozyloc,

What image URL is giving you that error? If you're getting a "not valid image" error then chances are the URL you're providing Yamipa with is not valid.

**Comment by ozyloc** [comment]
I use Imgur to upload the images, then copy the link and use either .png or .gif when uploading to Minecraft.

**Comment by josemmo** [comment]
Ok, but can you please post here one of the URLs that's giving you the "not valid image" error message so that I can try to debug the issue?

**Comment by ozyloc** [comment]
Oh, yeah here
https://imgur.com/a/h85yRpb

**Comment by josemmo** [comment]
That URL doesn't load a valid image file (JPG, PNG, GIF...), it's a webpage.
Downloading GIFs from Imgur is not straightforward (for instance, the proper URL for the image you provided is "https://imgur.com/download/98SP4fv", and Imgur's servers might block the request in somes cases).

I've added a small feature to Yamipa to properly handle these URLs without having to manually rewrite them. You can test it by downloading the latest snapshot ([v1.2.3-SNAPSHOT](https://github.com/josemmo/yamipa/releases/tag/v1.2.3-SNAPSHOT)).

**Comment by ozyloc** [comment]
Oh ok. Thank you!!!!!!
