### ISSUE TITLE
Some gifs not working

### ISSUE THREAD

**Issue by THEqqBULDIpp** [josemmo/yamipa#41]
There is only solid red colour instead of certain gifs.
After saving as gifs couple of cool loping animations from https://giphy.com and throwing them into my server there is **only solid red coluor visible** instead of these gifs. They play fine on my pc and everything but as soon as i copy them into **YamipaPlugin/images** they refuse to work

Examples that i have problem with:

- https://giphy.com/gifs/socialbakers-LP62GF82YvcuOuFJRD
- https://giphy.com/gifs/socialbakers-XEy1qyv7GdLpmqHEPV
- https://giphy.com/gifs/socialbakers-h2ejccV0wxvPnOch27
- https://giphy.com/gifs/socialbakers-cJXlcXMGevIIETJAYk

How does it look on server:
https://ibb.co/7Xx7Hkm

**Comment by josemmo** [comment]
Hello @THEqqBULDIpp,

Please attach the server logs. Also, check issue #30 to make sure this is not a duplicate.
