### ISSUE TITLE
Better security features

### ISSUE THREAD

**Issue by THEqqBULDIpp** [josemmo/yamipa#42]
Would it be possible to add some sort of check if players can place/break blocks in certain region based on worldguard flags?

Now everyone can just place images/gifs wherever they want. Even in regions protected by worldguard.
It would automatically work with protection stones plugin that i am using as well.

If there would be possibility to pull from worguard block-break and block-place flags and based on them allow players.

**Comment by josemmo** [comment]
Hi, @THEqqBULDIpp!

Support for WorldGuard has been implemented in the latest Yamipa version ([v1.2.4-SNAPSHOT](https://github.com/josemmo/yamipa/releases/tag/v1.2.4-SNAPSHOT)).
Do try it and let me know if it works. :)
