### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by rmr4k** [josemmo/yamipa#48]
Please add a file config.yml or lang.yml where all plugin messages will be, including over the hotbar. I really need to customize the messages in my own way!

**Comment by rmr4k** [comment]
=(

**Comment by josemmo** [comment]
Hello @rmr4k,

I'm prioritizing bugfixes and other features over this. I'll probably add translations and custom messages to the plugin, but not in the short term.

**Comment by NamiUni** [comment]
If you add a language file, it would be nice if the message is sent according to the client's language settings.
As far as I know, QuickShopReremake and CarbonChat use this system.
