### ISSUE TITLE
ANIM and GLOW flags don't work together

### ISSUE THREAD

**Issue by wtlgo** [josemmo/yamipa#55]
```
/yamipa give MikChan test.gif 1 4 2 ANIM,GLOW
```
The image glows but is not animated

```
/yamipa give MikChan test.gif 1 4 2 GLOW,ANIM
```

The image is animated but doesn't glow

**Comment by josemmo** [comment]
That's because you're overwriting the default flags (see #54).

If you want to give image items that glow, you need to **add** (not overwrite) the "GLOW" flag:
```
/yamipa give MikChan test.gif 1 4 2 +GLOW
```

Please, read the [documentation regarding flags](https://github.com/josemmo/yamipa#flags).
