### ISSUE TITLE
Picture can be removed by anyone

### ISSUE THREAD

**Issue by valenvaio** [josemmo/yamipa#60]
Please add a command that allows the player to change the flag to remove the picture by double-clicking from other players. Right now, no matter who owns the picture, if there is a flag, it can be removed by anyone. And with a flag the picture is removed only by command.

WE does not track the picture and it can be removed if there is no ban by the flag in the plugin -REMO .

**Comment by josemmo** [comment]
Hello @valenvaio,

What do you mean by "double-clicking from other players"?

Yamipa supports permissions, you don't have to grant the "yamipa.remove" permission to all your players. You have more details in the repository homepage.

**Comment by valenvaio** [comment]
I was talking about the fact that giving players the opportunity to set and remove pictures, then the carina inside the private can remove any player, not just the owner of the private. The option to remove permissions yamipa.remove for all players doesn't good, because the owner won't be able to remove the picture either.

**Comment by josemmo** [comment]
Wait, are you talking about image items (the ones a player can hold in its inventory and place by right-clicking a block) or the commands?

**Comment by valenvaio** [comment]
Yes, which the player can keep in his inventory.
