### ISSUE TITLE
Image not placed..

### ISSUE THREAD

**Issue by PJGamerr** [josemmo/yamipa#65]
I'm using Yamipa 1.2.6 and protocol 5.0.0-SNAPSHOT-b602 (the last one), every time I try to position an image in my actionbar "loading image" appears and so endlessly, the image is not positioned but if I try to place another one above in the same blocks the plugin tells me that an image already exists there .. even if it is not seen .. only this appears in the console: "[YamipaPlugin] Saved placed fake images to disk", how can I solve ?

![2022-11-08_14 42 43](https://user-images.githubusercontent.com/85345525/200581203-a28c6155-cc5b-4dc3-8c5c-4038fa318ae1.png)

**Comment by josemmo** [comment]
Hello @PJGamerr,

What server are you running (SpigotMC, PaperMC, Bukkit, etc)?

Please enable [verbose mode](https://github.com/josemmo/yamipa#configuration) and paste the full logs of your server when the bug occurs.

**Comment by LandOfPeeps** [comment]
This happened to me when I accidentally placed an image and it went through blocks, causing ghost blocks. It will say loading image endlessly until you relog.

I used a PaperMC server.

**Comment by josemmo** [comment]
@LandOfPeeps, I cannot reproduce the "ghosts blocks" think you mention. Works fine under PaperMC 1.19.3 build 348:

![2022-12-21_19 20 44](https://user-images.githubusercontent.com/4470267/208976739-97f2d12e-499a-4c19-837e-2c2f61dbe6e3.png)

**Comment by josemmo** [comment]
Closed due to inactivity.
