### ISSUE TITLE
1.19.3 Geyser Compatibility Issue

### ISSUE THREAD

**Issue by LandOfPeeps** [josemmo/yamipa#68]
When Yamipa images are rendered by a player no matter Java or Bedrock with the latest GeyserMC installed, the player will get kicked from the server.

**Full console error:**
https://mclo.gs/TcE44DW

**Comment by josemmo** [comment]
Hi,

Yamipa is not compatible with GeyserMC or similar packet translators.

**Comment by LandOfPeeps** [comment]
Actually, after your recent plugin update I decided to just give it a try and it worked fine, even GIFs on GeyserMC. Seems like it's just a compatibility issue with 1.19.3 in general before

**Comment by josemmo** [comment]
Good to know, thanks for the info!

Still, Yamipa is not intended to be used with packet translators. So, nothing is stopping you or anyone from using GeyserMC, but bear it mind it might not work properly.
