### ISSUE TITLE
Commands not found

### ISSUE THREAD

**Issue by CallMeAndre2910** [josemmo/yamipa#73]
Hi, I have a problem.
I installed the plugin on my server but when I go to run the commands it can't find them.
Yet if I do /pl it finds me both ProtocolLib and Yamipa working plugins. How can I do?

**Comment by josemmo** [comment]
Do you have the proper permissions? By default, only server OPs can see and run Yamipa commands as [explained here](https://github.com/josemmo/yamipa#permissions).
Can you run "/yamipa" from the server console?

**Comment by josemmo** [comment]
Does this happen only with Yamipa subcommands or with commands for any other plugin?

**Comment by CallMeAndre2910** [comment]
Only yamipa's commands don't work

**Comment by josemmo** [comment]
Ok, then I need more info to debug this:

- What server are you running? SpigotMC, Bukkit, PaperMC, etc.
- What Minecraft version are you on? 1.19.2, 1.19.3, etc.
- What version of ProtocolLib are you using? 4.8.0, 5.0.0-SNAPSHOT-b608, etc.
- What other plugins do you have installed?

**Comment by CallMeAndre2910** [comment]
- Spigot
- 1.19.2
- 1.0.4-SNAPSHOT
- SkinRestorer, ProtocolLib, Yamipa
-

**Comment by josemmo** [comment]
> 1.0.4-SNAPSHOT

Wait, you mean you're using Yamipa v1.0.4-SNAPSHOT? ProtocolLib doesn't have an artifact/release with that version.

**Comment by CallMeAndre2910** [comment]
It didn't even work with the latest version. I changed it because I had found a video where he said to use this version.

**Comment by josemmo** [comment]
Well, there's you problem, you're using a Yamipa version that's quite outdated ;)

Download the [latest release](https://github.com/josemmo/yamipa/releases/latest) and also make sure you're using the [latest development build](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) from ProtocolLib.

**Comment by CallMeAndre2910** [comment]
Okay thanks now it works
