### ISSUE TITLE
Support for 1.19.3?

### ISSUE THREAD

**Issue by AzCreep** [josemmo/yamipa#75]
I have this server on 1.19.3 but it keeps showing this error idk if it's a new thing recently but seems to be now 

here is the error: https://pastebin.com/aLYhZCQ9

i hope it does get fixed love this plugin!!

**Comment by josemmo** [comment]
Hello @AzCreep,

You need to download the [latest dev build of ProtocolLib](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) to fix that error.
