### ISSUE TITLE
Can't remove image when image was placed in land claimed with GriefPrevention

### ISSUE THREAD

**Issue by MarcelskyXD** [josemmo/yamipa#76]
I cannot remove a image i have placed when the image is in a area claimed with GriefPrevention.

**Comment by josemmo** [comment]
Hello @MarcelskyXD,

- What server are you running? SpigotMC, Bukkit, PaperMC, etc.
- What Minecraft version are you on? 1.19.2, 1.19.3, etc.
- What version of ProtocolLib are you using? 4.8.0, 5.0.0-SNAPSHOT-b608, etc.
- What version of GriefPrevention are you using?
- What error message are you getting?
- What error trace do your server logs contain (if any)?

**Comment by MarcelskyXD** [comment]
> Hello @MarcelskyXD,
> 
> * What server are you running? SpigotMC, Bukkit, PaperMC, etc. Purpur (paper fork)
> * What Minecraft version are you on? 1.19.2, 1.19.3, etc. 1.19.3
> * What version of ProtocolLib are you using? 4.8.0, 5.0.0-SNAPSHOT-b608, etc. 5.0.0-SNAPSHOT-b608
> * What version of GriefPrevention are you using? 16.18
> * What error message are you getting? no error, i just cant break it
> * What error trace do your server logs contain (if any)? none

**Comment by josemmo** [comment]
No error when trying to remove it? That's weird...

Please paste here the output from the `/image describe` command of the image you cannot remove.

**Comment by josemmo** [comment]
Hi @MarcelskyXD,

This should be fixed in the next pre-release ([v1.2.8-SNAPSHOT](https://github.com/josemmo/yamipa/releases/tag/v1.2.8-SNAPSHOT)).

Give it a try and let me know if it worked :)

**Comment by MarcelskyXD** [comment]
For now i will close this issue, i will re open it if the pre release version does not work.
