### ISSUE TITLE
Images unloading with chunk borders

### ISSUE THREAD

**Issue by ampersandhd** [josemmo/yamipa#77]
Images are unloading, when switching chunks.
Why are not all images visible at the same time?

https://user-images.githubusercontent.com/109629062/212432408-e72eef0f-5cd7-460b-a451-f090a5870504.mp4

Yamipa 1.2.7 on Paper 1.19.2.

**Comment by josemmo** [comment]
Hi @ampersandhd,

What's the view distance for your server/world?

**Comment by ampersandhd** [comment]
Server Properties are Set to 8 Chunks and we are using viewdistancetweaks for a Dynamic Farther view. The Blocks behind the images are rendered, too. The problem is also not happening everywhere on our Server.

**Comment by josemmo** [comment]
viewdistancetweaks must be lowering the view distance for plugins calling `world.getViewDistance()`, because Yamipa makes use of that method to determine which images should be loaded when nearby a player:

https://github.com/josemmo/yamipa/blob/1fd4319454e21da715f0806af78e87d033fcfa17/src/main/java/io/josemmo/bukkit/plugin/renderer/WorldAreaId.java#L59-L71

I'll try to investigate it further.

**Comment by ampersandhd** [comment]
We are at Viewdistancetweaks 1.5.3 - we Test, If updating fixes the issue

**Comment by ampersandhd** [comment]
Issue still persists with ViewDistanceTweaks (v1.5.4).
Here's the config:

`# How long in ticks should we wait before starting the checking tasks following the plugin's start up?
#  * This is useful when using the 'mixed' or 'reactive' adjustment modes where it is desirable to ignore the server's
#    performance in the first few minutes following a restart.
start-up-delay: 2400

# How many checks in a row that say to increase the simulation or view distance should be required before an increase
# actually occurs?
#  * This is useful as it guards against the following kind of case: A player leaves and the view distance is
#    increased, but the player returns three minutes later and the view distance is lowered to its previous value.
#  * Since increasing the view distance can cause lag-spikes for players with poorer connections, it is
#    recommended to keep this value relatively high.
passed-checks-for-increase: 10

# How many checks in a row that say to decrease the simulation or view distance should be required before a decrease
# actually occurs?
passed-checks-for-decrease: 1

# Should we send a message to the console when we change the simulation or view distance?
log-changes: false

# These settings can be specified per world. If a world is not specified or if a setting is missing, it will use the
# settings listed under the default section.
world-settings:
  default:
    # These settings concern the simulation distance of this world.
    simulation-distance:
      # Should we not manage the simulation distance in this world?
      #  * Note: Even if excluded, the world's chunks will be counted for the purpose of adjusting the simulation distance
      #    of other worlds. If you do not want this, also be sure to set the chunk-weight to 0.
      exclude: false

      # What should the absolute minimum simulation distance be in this world?
      minimum-simulation-distance: 6

      # What should the absolute maximum simulation distance be in this world?
      maximum-simulation-distance: 32

    # These settings concern the view distance of this world.
    view-distance:
      # Should we not manage the view distance in this world?
      #  * Note: Even if excluded, the world's chunks will be counted for the purpose of adjusting the view distances
      #    of other worlds.
      exclude: false

      # What should the absolute minimum view distance be in this world?
      minimum-view-distance: 8

      # What should the absolute maximum view distance be in this world?
      maximum-view-distance: 32

    # Relative to the other worlds, how 'heavy' is a chunk on performance?
    #  * For example: In the End dimension, about half of the chunks you encounter are void and so have very little
    #    impact on performance. For this reason, you may want to set the chunk-weight of the End to 0.5.
    chunk-weight: 1

    # These settings concern how we count the number of chunks in this world.
    chunk-counter-settings:
      # When two players are near each other, the chunks they load can overlap. Should we not double count the chunks
      # that are overlapping?
      exclude-overlap: true

#  world_the_end:
#    simulation-distance:
#      minimum-simulation-distance: 8
#      maximum-simulation-distance: 10
#    chunk-weight: 0.5
`

Any ideas for a fix or reproduction?

**Comment by ampersandhd** [comment]
I am going to Paste the Original File Here. Could you maybe view the issue live on our server, Too?

**Comment by ampersandhd** [comment]
https://pastebin.com/i2uqNWmK

**Comment by josemmo** [comment]
Still cannot reproduce the bug :(

I do, however, now have an idea as to what the cause of the bug might be, which is that changing the [`WorldAreaId`](https://github.com/josemmo/yamipa/blob/a5c53d7ec5b15174d7b7ca80133329ebe77df055/src/main/java/io/josemmo/bukkit/plugin/renderer/WorldAreaId.java) size at runtime might yield unexpected results.

I'm going to prepare a patch and let you know when it's ready so you can try it.

**Comment by ampersandhd** [comment]
I Suppose, you Need More than one sind Player to reproduce it. So that chunks are loading and unloading within the plugin. Awaiting your fix.

**Comment by josemmo** [comment]
@ampersandhd you can now try [v1.2.8-SNAPSHOT-b2](https://github.com/josemmo/yamipa/releases/tag/v1.2.8-SNAPSHOT-b2).

**Comment by ampersandhd** [comment]
This snapshot seems to fix the issue. Great Job!
