### ISSUE TITLE
if the player rides on the minecart, then he will not even see the image up close

### ISSUE THREAD

**Issue by GenifeG** [josemmo/yamipa#78]
Tested many times, even on a clean server. The problem exists.

build a railroad ~200 blocks from the picture and start riding. When you arrive - the picture will not be displayed

**Comment by GenifeG** [comment]
1.19.2, purpur

**Comment by Kinboise** [comment]
Same issue on my 1.19.3 paper server.

**Comment by josemmo** [comment]
Thanks for reporting this! It will be fixed on the next release.
