### ISSUE TITLE
Feature request: Rotation?

### ISSUE THREAD

**Issue by Kinboise** [josemmo/yamipa#80]
Since images are fake item frame entities (as far as I know), it would be great to allow:
### item-rotation
Useful for image of an arrow (won't have to make four images for four directions), etc.
### entity rotation (free pitch and yaw)
Useful for roadsigns on 45° diagonal roads, etc.

*Thanks!*

**Comment by josemmo** [comment]
Hello @Kinboise,

At this time I don't have plans to implement rotation. IMO, it will add too much complexity to both the code and the usage (i.e., new arguments will be needed for the "place" command).
