### ISSUE TITLE
Limit player maps?

### ISSUE THREAD

**Issue by catches** [josemmo/yamipa#83]
Possible to limit the amount of maps a player can make? Like if they attempt to place more than 5 maps, it would say, "You have more than 5 maps, please remove some to place more." Or something like that.

**Comment by josemmo** [comment]
> Also if possible, allow other players to remove images instead of using the command, just like clicking on the image directly instead.

This feature is already implemented, it's called **image items** and can be used through the `/image give` command.

---

> Possible to limit the amount of maps a player can make?

On a similar note, this might be better achieved by not letting players use the `/image place` command and instead give them a limited amount of image items.
