### ISSUE TITLE
Pasted images affect other images

### ISSUE THREAD

**Issue by cubilization** [josemmo/yamipa#84]
Hi Yamipa team,

I have an issue where placed images at Area A would also be duplicated/placed at Area B which is a different image
The images seem to stack on top of the other even if they are completely different images.

See screenshot of my portal: https://gyazo.com/727fe7cb6bf0058a39a48a0a8ba3229f
The duplication: https://gyazo.com/f2bb8616b868f706326a739e4692f663

**Comment by cubilization** [comment]
> Hello @cubilization,
> 
> I don't fully understand the issue. You mean when you place two images next to each other they overlap?
> 
> What version of Yamipa are you using? What server (Spigot/PaperMC, etc) + version, including build number?

Hi Jose, 

Im using Paper 1.19.3 Build #407,
And latest Yamipa from Spigot

No, not placing 2 images next to eachother.
If I place a new/separate image at a different location, the 1st image I placed shows as overlapping on the 2nd image, which was pasted nowhere near the 1st image.


I place (blueportal.gif) at my teleport portal,
Then I go to the other side of my spawn hub
to place (ranks.jpeg) ~ 2 different images/2 different locations 

When I leave the area and come back,
Blueportal.gif is somehow on top of ranks.jpeg,
overlapping it even if I didnt paste it there

(as seen in screenshots above The blue portal image is half loaded, but in the 2nd screenshot it is somehow covering my Ranks images)

The red section is part of the blueportal.gif

**Comment by josemmo** [comment]
In the case of the second screenshot, I see you're placing the image on top of some text. What plugin is adding that text?

**Comment by cubilization** [comment]
The issue is when I place **two different images** at **different locations** The first image randomly spawns on top of the second image. There is no other plugin, and I am not placing an image on top of another image.

**Comment by cubilization** [comment]
I am simply saying the first image somehow also appears on top of the 2nd image I place - Which are at both 2 different locations.
I am not placing images on top of eachother.
