### ISSUE TITLE
MultiPaper version

### ISSUE THREAD

**Issue by YTiceice** [josemmo/yamipa#88]
Could you please make a version suitable for MultiPaper?
Generated images will not be displayed in sync across different servers...

**Comment by josemmo** [comment]
I'm not familiar with MultiPaper. Could you provide more details on the setup you have? Do you have a shared directory will the images for all server instances?

Are you getting any exception thrown? Or any logs?

**Comment by YTiceice** [comment]
I have the folder data of the sync plug-in, and there is no error or exception on the console. I have temporarily switched to other plug-ins that support MySQL to achieve it. If you make one, please let me know, I will be very grateful.
