### ISSUE TITLE
[feature-request] support subfolders storage for images

### ISSUE THREAD

**Issue by RedstoneFuture** [josemmo/yamipa#90]
I've been using Yamipa for a while now and so far I really like the plugin. It would be very nice if we could store the images in subfolders so that we can better manage the media data in larger projects.

Other big image plugins also support subfolders and that's really good. The "file" argument can then simply contain the relative path (e.g. "/testfolder/filenme.png"). This is basically sufficient.

**Comment by josemmo** [comment]
Hello @RedstoneFuture,

This feature was previously discussed in #28.

**Comment by josemmo** [comment]
Implemented in 0edd1f28e50eddd9e328965e4e3ff65cff418292, currently being tested.

**Comment by RedstoneFuture** [comment]
Nice to hear. If this works, I can also use the plugin on a larger scale. Thank you very much. :)

**Comment by josemmo** [comment]
Hi, @RedstoneFuture!

You can download the next experimental release here: https://github.com/josemmo/yamipa/releases/tag/v1.3.0-SNAPSHOT
