### ISSUE TITLE
[Feature Request] extra admin features

### ISSUE THREAD

**Issue by LadyHaley** [josemmo/yamipa#91]
In the interest server moderation, would it be possible to add a couple of commands
a command to telepport to specific pictures, and a command to see who created what picture

**Comment by josemmo** [comment]
Hello @LadyHaley,

That would require heavily reworking the `ImageStorage` service. I've seen other feature requests that would also need that (#88, #90), so maybe it's worth the effort.

Still, sounds like a good idea. I'll add it to the backlog, but don't expect it anytime soon.

**Comment by josemmo** [comment]
Added options in [v1.3.0](https://github.com/josemmo/yamipa/releases/tag/v1.3.0) to restrict which image files can be placed/downloaded by a given player to improve server moderation.
