### ISSUE TITLE
Yamipa in 1.20.1

### ISSUE THREAD

**Issue by itsNightly** [josemmo/yamipa#98]
Hi. I see that the latest version of the plugin from Saturday supports version 1.20, but the protocollib plugin is required. I didn't find it for version 1.20. What should I do?🤨

Thank you in advance

**Comment by josemmo** [comment]
Hi!

Yamipa v1.2.11 has been tested to work in MC 1.20.1 with the latest stable from ProtocolLib (v5.0.0), which you can download from [this link](https://github.com/dmulloy2/ProtocolLib/releases/tag/5.0.0).
