### ISSUE TITLE
Images randomly dissappear

### ISSUE THREAD

**Issue by LilBamaBeets** [josemmo/yamipa#99]
Set images will just randomly dissappear. I believe that they are still technically there but visually arent if that makes sense

**Comment by josemmo** [comment]
Hello @LilBamaBeets,

- What server are you using? _SpigotMC, Bukkit, PaperMC, etc._
- What server version? _e.g., MC 1.20.1 build 60_
- What ProtocolLib version are you using? _e.g., v5.0.0_
- On what version of Yamipa does this bug occur? _e.g., v1.2.11_
- What steps need to be followed to reproduce the bug?
- Does Yamipa raise any warning or error entries in the server logs? If so, paste them in this thread.

**Comment by LilBamaBeets** [comment]
What server are you using? SpigotMC, Bukkit, PaperMC, etc.

Paper

What server version? e.g., MC 1.20.1 build 60

MC 1.20.1 Build 45

What ProtocolLib version are you using? e.g., v5.0.0

5.1.0-SNAPSHOT-654

On what version of Yamipa does this bug occur? e.g., v1.2.11

1.2.11

What steps need to be followed to reproduce the bug?

From what I've seen the bug doesn't have a specific trigger it jut happens after a few days of the server running. It does seem to fix when server is restarted but it then will disappear again

Does Yamipa raise any warning or error entries in the server logs? If so, paste them in this thread.

Nope

**Comment by Agaloth** [comment]
This still happens for me as well updating to the latest protocol lib didn't fix it.

What server are you using? SpigotMC, Bukkit, PaperMC, etc.
This server is running Pufferfish+ version git-PufferfishPlus-7 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 19b9135 on HEAD)

What ProtocolLib version are you using? e.g., v5.0.0
ProtocolLib version 5.1.0-SNAPSHOT-654

On what version of Yamipa does this bug occur? e.g., v1.2.11
YamipaPlugin version 1.2.11

Does Yamipa raise any warning or error entries in the server logs? If so, paste them in this thread.
No

**Comment by josemmo** [comment]
I'm unable to reproduce this bug :/

To fix it, we need to come up with a set of steps that always (or almost always) trigger the bug, like staying still in a chunk for a few minutes (I already tried that one with no luck). Any ideas?

Also, do you have any other plugins that might be triggering this bug? @LilBamaBeets, @Agaloth, we can try to find common plugins in your server, if that's ok with you.

**Comment by Agaloth** [comment]
> I'm unable to reproduce this bug :/
> 
> To fix it, we need to come up with a set of steps that always (or almost always) trigger the bug, like staying still in a chunk for a few minutes (I already tried that one with no luck). Any ideas?
> 
> Also, do you have any other plugins that might be triggering this bug? @LilBamaBeets, @Agaloth, we can try to find common plugins in your server, if that's ok with you.

Yeah that's fine with me, here is my plugin list:

[10:07:15 INFO]: Server Plugins (124):
[10:07:15 INFO]: Paper Plugins:
[10:07:15 INFO]:  - MarriageMaster, RoseStacker
[10:07:15 INFO]: Bukkit Plugins:
[10:07:15 INFO]:  - AdvancedEnchantments, AdvancedVanish, ajLeaderboards, *ajStartCommands, Analyse, ArmorTrim, BattlePass, BiomeChanger, BlockLocker, Brewery
[10:07:15 INFO]:  BuycraftX, ChatComplete, ChatSentry, Chunky, ChunkyBorder, Citizens, CMILib, ColoredAnvils, *CommandRegions, CommandWhitelist
[10:07:15 INFO]:  CommunityGoals, CoreProtect, CyberWorldReset, DeathLocation, DecentHolograms, DeluxeAnnounce, DeluxeCombat, DeluxeMenus, DeluxeSellwands, DeluxeTags
[10:07:15 INFO]:  DiscordSRV, DiscordSRV-Staff-Chat, EliteArmor, EnderDragonTweaks, Essentials, EssentialsSpawn, FarmControl, FastAsyncWorldEdit, FreedomChat, GSit
[10:07:15 INFO]:  HeadDatabase, InteractiveChat, InteractiveChatDiscordSrvAddon, InventoryRollbackPlus, InvisibleItemFrames, ItemCommands, ItemEdit, ItemsAdder, ItemTag, JakesRTP
[10:07:15 INFO]:  JetsAntiAFKPro, KauriVPN, KixsChatGames, LeaderboardRewards, Lib1711, LibsDisguises, LiteBans, LoneLibs, LuckPerms, MapTowny
[10:07:15 INFO]:  mcMMO, McmmoGui, MCPets, MessageSounds, ModelEngine, Multiverse-Core, Multiverse-Inventories, *MVdWPlaceholderAPI, MyCommand, MythicMobs
[10:07:15 INFO]:  NBTAPI, NightMarket, NightVision, OpenInv, PinataParty, Pl3xMap, PlaceholderAPI, PlayerAuctions, PlayerKits, PlayerPoints
[10:07:15 INFO]:  PlayerVaults, PlayerWarps, PlugManX, ProCosmetics, ProtocolLib, PyroFishingPro, PyroLib, QuickShop-Hikari, RandomEvents, RankDisplay
[10:07:15 INFO]:  RankupMenu, RoseLoot, SafariNet, *ServerTutorialPlus, ShopGUIPlus, ShopGUIPlus-SellGUI, Shopkeepers, spark, SpawnerShutdown, SpecializedCrates
[10:07:15 INFO]:  *STN-Studios-API, StoreGoal, SuperbVote, TAB, Towny, TownyFlight, TownyMenu, TownyWild, UltimateAutoRestart, Vault
[10:07:15 INFO]:  Vehicles, VentureChat, ViaBackwards, ViaVersion, VillagerOverhaul, voicechat, Votifier, Vulcan, WorldGuard, WorldGuardExtraFlags
[10:07:15 INFO]:  XPBoost, YamipaPlugin

**Comment by LilBamaBeets** [comment]
Sure, heres my plugin list:
CoreProtect
Essentials
LuckPerms
Multiverse-Core
ProtocolLib
Skript 
WorldEdit 
YamipaPlugin

**Comment by uqlel** [comment]
It also happens to me. Everything worked fine for 7 days and then images started dissappearing (yesterday my friend saw the most of the images dissapear, today they are all gone.

**Comment by uqlel** [comment]
After a restart everything worked normally. So images disappear from the world, but they don't disappear from the images.dat, and after a restart the plugin places the images again.

**Comment by josemmo** [comment]
I've created a test server with the following specs:
- [paper-1.20.1-60.jar](https://api.papermc.io/v2/projects/paper/versions/1.20.1/builds/60/downloads/paper-1.20.1-60.jar)
- [ProtocolLib v5.0.0-SNAPSHOT-b657](https://ci.dmulloy2.net/job/ProtocolLib/657/artifact/build/libs/ProtocolLib.jar)
- [YamipaPlugin v1.2.11](https://github.com/josemmo/yamipa/releases/download/v1.2.11/YamipaPlugin-1.2.11.jar)
- [CoreProtect v21.3](https://cdn.modrinth.com/data/Lu3KuzdV/versions/mvLpRWww/CoreProtect-21.3.jar)
- [EssentialsX v2.20.0](https://github.com/EssentialsX/Essentials/releases/download/2.20.0/EssentialsX-2.20.0.jar)
- [LuckPerms-Bukkit v5.4.98](https://download.luckperms.net/1512/bukkit/loader/LuckPerms-Bukkit-5.4.98.jar)
- [Multiverse-Core v4.3.1](https://dev.bukkit.org/projects/multiverse-core/files/3462546/download)
- [WorldEdit-Bukkit v7.2.15](https://dev.bukkit.org/projects/worldedit/files/4586220/download)

After placing an animated image and leaving a player AFK for 4 hours straight, the image was still playing with no issues.
Unless someone finds a systematic way of reproducing this bug, there's not much else I can do to debug this further :/

**Comment by LilBamaBeets** [comment]
have you tried afking but with the player not having the image loaded? i think it only happens for me when im not near any images

**Comment by josemmo** [comment]
Hi, @LilBamaBeets!

Could you elaborate on that? You mean placing an image, going far away from it, afking for hours and then coming back to where it was placed?

**Comment by LilBamaBeets** [comment]
yeah basically

**Comment by josemmo** [comment]
@LilBamaBeets afked for 4 hours, still no issue.

**Comment by LilBamaBeets** [comment]
maybe try leaving it for a day or 2?

**Comment by josemmo** [comment]
lol nope

**Comment by LilBamaBeets** [comment]
pain i'll try get you some more info to try recreate it

**Comment by Kikisito** [comment]
I'm also having this issue. It's like the plugin stops working because after some hours all images disappear. If I reload Yamipa using PlugManX and I rejoin the server, all images reappears.

Using Paper 1.20.1 #100, Yamipa 1.2.11 and ProtocolLib 5.1.0-SNAPSHOT-654

**Comment by LilBamaBeets** [comment]
the bug seems to be random as i have had a server running for a month and 3 days and only just had images dissappear

**Comment by Agaloth** [comment]
@josemmo I could let you use my server if it helps find the bug? I get this issue every day.

**Comment by Agaloth** [comment]
Some extra info: 
My /cache folder is over 1.5GB and has 501 files
My /image folder is over 76MB and has 198 files
My images.dat is 27kb
